  attach-binaries:
    needs: [build-ubuntu, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Download Ubuntu Artifact
      uses: actions/download-artifact@v2
      with:
        name: litroulette-ubuntu
        path: ubuntu-artifact

    - name: Download macOS Artifact
      uses: actions/download-artifact@v2
      with:
        name: litroulette-macos
        path: macos-artifact

    - name: Upload Ubuntu Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./ubuntu-artifact/litroulette
        asset_name: litroulette-ubuntu
        asset_content_type: application/octet-stream

    - name: Upload macOS Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./macos-artifact/litroulette
        asset_name: litroulette-macos
        asset_content_type: application/octet-stream